INSERT INTO CATEGORY(NAME) VALUES('Nabaca');
INSERT INTO CATEGORY(NAME) VALUES('Fasada');
INSERT INTO CATEGORY(NAME) VALUES('Krov');
INSERT INTO CATEGORY(NAME) VALUES('Oluk');
INSERT INTO CATEGORY(NAME) VALUES('Malterisanje');
INSERT INTO CATEGORY(NAME) VALUES('Salovanje');
INSERT INTO CATEGORY(NAME) VALUES('Ograda');


--INSERT INTO USER(USERNAME,POSTANSKI_BROJ,LONGITUDE,LATITUDE,UDALJENOST,TYPE,CATEGORY_NAME,MAIL) VALUES('firma1',79220,1,1,3,1,'Nabaca','milos@localhost');
--INSERT INTO USER(USERNAME,POSTANSKI_BROJ,LONGITUDE,LATITUDE,UDALJENOST,TYPE,CATEGORY_NAME,MAIL) VALUES('firma2',79220,2,2,3,1,'Nabaca','1@localhost');
--INSERT INTO USER(USERNAME,POSTANSKI_BROJ,LONGITUDE,LATITUDE,UDALJENOST,TYPE,CATEGORY_NAME) VALUES('firma3',79220,3,3,3,1,'Fasada');
--INSERT INTO USER(USERNAME,POSTANSKI_BROJ,LONGITUDE,LATITUDE,UDALJENOST,TYPE) VALUES('user1',79220,2,2,0,0);


--INSERT INTO CATEGORY_USERS(USERS_USERNAME,CATEGORY_NAME) VALUES ('firma1','Nabaca');
--INSERT INTO CATEGORY_USERS(USERS_USERNAME,CATEGORY_NAME) VALUES ('firma2','Nabaca');
--INSERT INTO CATEGORY_USERS(USERS_USERNAME,CATEGORY_NAME) VALUES ('firma3','Fasada');

