INSERT INTO CATEGORY(NAME) VALUES('Nabaca');
INSERT INTO CATEGORY(NAME) VALUES('Fasada');
INSERT INTO CATEGORY(NAME) VALUES('Krov');
INSERT INTO CATEGORY(NAME) VALUES('Oluk');
INSERT INTO CATEGORY(NAME) VALUES('Malterisanje');
INSERT INTO CATEGORY(NAME) VALUES('Salovanje');
INSERT INTO CATEGORY(NAME) VALUES('Ograda');